name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-yarn@v3
        with:
          yarn-version: '1.22.19'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test